### ISSUE TITLE
[BUG] Settings back to default after server start

### ISSUE THREAD

**Issue by CodeWithCharles** [jupster/FASTER1.9#2]
**Describe the bug**  
Settings seems to revert to default after a server start.

**To Reproduce**  
Steps to reproduce the behaviour:
1. Create a server
2. Change some mission settings
3. Save those settings
4. Start the server. The settings are back to default

**Expected behaviour**  
The settings should not go back to default

**Actual behaviour**  
On start, the mission settings were not the one we had set. For example, the stamina bar was shown.

**OS Version (required):**  
 - OS: Windows Server 2022
 - FASTER Version [1.9d_145.3]

**Additional context**  
Saving the settings works fine.

**Comment by CodeWithCharles** [comment]
Here is our current config as discussed : 
![image](https://github.com/jupster/FASTER1.9/assets/47571538/c525ed82-d5fc-4e1b-8a77-03ec17c2e3a3)
![image](https://github.com/jupster/FASTER1.9/assets/47571538/4eeacdf3-ab96-4084-82ee-5b9a60cd6ced)
![image](https://github.com/jupster/FASTER1.9/assets/47571538/bb6e062f-8723-47fe-88d0-baedcb30ca15)

For some reason my division commander has been able to save settings for this particular server. Doesn't work for the others tho

**Comment by jupster** [comment]
Can't repro this. Since it worked fine for one of your team it does seem a bit weird. What version did it last work find on?
