### ISSUE TITLE
[BUG] Interface breaking after some time running

### ISSUE THREAD

**Issue by CodeWithCharles** [jupster/FASTER1.9#3]
**Describe the bug**  
The interface is breaking when the software runs for a bit of time.

**To Reproduce**  
Steps to reproduce the behaviour:
1. Launch the software
2. Use it a bit, create a server, change some settings, etc.
3. Can leave it running
4. Go back to it after 10 min, interface should be broken

**Expected behaviour**  
The interface should not be broken

**Actual behaviour**  
Some fonts are breaking, some things are turning white, + button to add a server disappears etc.

**Screenshots**  
![image](https://github.com/jupster/FASTER1.9/assets/47571538/06136b63-a833-4037-8655-c41828de3d90)

**OS Version (required):**  
 - OS: Windows Server 2022
 - FASTER Version [1.9d_145.3]

**Comment by jupster** [comment]
This is an issue with WPF itself, yeah. 
It has to do with how the graphic driver of RDP handles the UI of apps.
